version: "3.7"

services:
  app:
    container_name: app-dev-container
    image: app-dev-image
    build: 
      context: .  
      target: development
    volumes:
      - ./src:/app/src
    ports: 
      - 3000:3000
